---
apiVersion: v1
data:
  CLI_VERSION: v0.12.34-1-g8214573b
  CLUSTER_NAME: {{ .Values.clusterName }}
  IMAGE_PULL_POLICY: {{ .Values.image.pullPolicy }}
  IMAGE_PULL_SECRETS: ""
  IMAGE_REGISTRY: {{ .Values.image.registry }}
  IMAGE_TAG: {{ .Values.image.tag }}
  INSTANCE_ID: '{{ ( printf "%s-%s" .Values.clusterName .Release.Namespace ) }}'
  LOG_LEVEL: {{ .Values.logLevel }}
  TELEMETRY_INTERVAL: 2s
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: speedscale-operator
  namespace: {{ .Release.Namespace }}
