# An API key is required to connect to the Speedscale cloud.
# If you need a key email support@speedscale.com.
apiKey: ""
# Speedscale domain to use.
appUrl: "app.speedscale.com"

# The name of your cluster.
clusterName: "my-cluster"

# Speedscale components image settings.
image:
  registry: gcr.io/speedscale
  tag: v1.1.134
  pullPolicy: Always

# Log level for Speedscale components.
logLevel: "info"

# Namespaces to be watched by Speedscale Operator.
namespaceSelector: {}

# Instructs operator to deploy resources necessary to interact with your cluster from the Speedscale dashboard.
dashboardAccess: true

# Filter Rule to apply to the Speedscale Forwarder
filterRule: "standard"

# Data Loss Prevention settings.
dlp:
  # Instructs operator to enable data loss prevention features
  enabled: false

  # Configuration for data loss prevention
  config: "standard"

# Example:
# annotation.first: value
# annotation.second: value
globalAnnotations: {}

# A full affinity object as detailed: https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity
affinity: {}

# The list of tolerations as detailed: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

# A nodeselector object as detailed: https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/
nodeSelector: {}
